apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-sender-agent-python
  namespace: datadog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-sender-agent-python
  template:
    metadata:
      labels:
        app: metric-sender-agent-python
    spec:
      containers:
        - name: app
          image: <ACCOUNT_ID>.dkr.ecr.us-east-2.amazonaws.com/metric-sender-with-agent-python:vector-v1
          imagePullPolicy: Always
          env:
            # Point to Vector Service (cross-namespace DNS)
            - name: DOGSTATSD_HOST
              value: "vector.vector.svc.cluster.local"
            - name: DOGSTATSD_PORT
              value: "9125"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits:   { cpu: 200m, memory: 128Mi }
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
