role: "Agent"
service:
  enabled: false

podHostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

containerPorts:
  - name: statsd
    containerPort: 9125
    protocol: UDP

env:
  - name: CLUSTER_ENV
    value: dev
  - name: DD_API_KEY
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: api-key

customConfig:
  data_dir: /vector-data-dir
  sources:
    statsd:
      type: statsd
      address: "0.0.0.0:9125"
      mode: udp
  transforms:
    add_env_identifier_tags:
      type: remap
      inputs: ["statsd"]
      source: |
        .tags.env = get_env_var!("CLUSTER_ENV")
    aggregate_statsd:
      type: aggregate
      inputs: ["add_env_identifier_tags"]
      interval_ms: 10000   
      mode: Auto

  sinks:
    datadog_metrics:
      type: datadog_metrics
      inputs: ["aggregate_statsd"]
      default_api_key: "${DD_API_KEY}"
      site: "us5.datadoghq.com"
    console:
      type: console
      inputs: ["aggregate_statsd"]
      encoding:
        codec: json


