apiVersion: v2
name: arc-stack
description: Deploys both GitHub ARC controller and runner set
type: application
version: 0.1.0

dependencies:
  - name: gha-runner-scale-set
    version: 0.12.0
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
  - name: gha-runner-scale-set-controller
    version: 0.12.0
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
