apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: arc
    meta.helm.sh/release-namespace: arc-systems
  creationTimestamp: "2025-06-23T20:37:03Z"
  generation: 1
  labels:
    actions.github.com/controller-service-account-name: arc-gha-rs-controller
    actions.github.com/controller-service-account-namespace: arc-systems
    app.kubernetes.io/instance: arc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/namespace: arc-systems
    app.kubernetes.io/part-of: gha-rs-controller
    app.kubernetes.io/version: 0.12.0
    helm.sh/chart: gha-rs-controller-0.12.0
  name: arc-gha-rs-controller
  namespace: arc-systems
  resourceVersion: "71011"
  uid: 3ce27af5-b987-4e1a-a92c-5359bd4d0bb7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: arc
      app.kubernetes.io/name: gha-rs-controller
      app.kubernetes.io/namespace: arc-systems
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: arc
        app.kubernetes.io/name: gha-rs-controller
        app.kubernetes.io/namespace: arc-systems
        app.kubernetes.io/part-of: gha-rs-controller
        app.kubernetes.io/version: 0.12.0
    spec:
      containers:
      - args:
        - --auto-scaling-runner-set-only
        - --log-level=debug
        - --log-format=text
        - --runner-max-concurrent-reconciles=2
        - --update-strategy=immediate
        - --listener-metrics-addr=0
        - --listener-metrics-endpoint=
        - --metrics-addr=0
        command:
        - /manager
        env:
        - name: CONTROLLER_MANAGER_CONTAINER_IMAGE
          value: ghcr.io/actions/gha-runner-scale-set-controller:0.12.0
        - name: CONTROLLER_MANAGER_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ghcr.io/actions/gha-runner-scale-set-controller:0.12.0
        imagePullPolicy: IfNotPresent
        name: manager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: arc-gha-rs-controller
      serviceAccountName: arc-gha-rs-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: tmp
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-23T20:37:03Z"
    lastUpdateTime: "2025-06-23T20:37:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-23T20:37:03Z"
    lastUpdateTime: "2025-06-23T20:37:03Z"
    message: ReplicaSet "arc-gha-rs-controller-78b5f4b45b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1