apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-prod
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    repoURL: https://github.com/ibugithub/trykube.git
    targetRevision: main
    path: argo-repo/chartApp
    helm:
      values: |
        replicaCount: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
