apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: learning-exercise-namespace

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml

configMapGenerator:
  - name: learning-exercise-app-config
    behavior: replace
    literals:
      - WELCOME_MESSAGE=Welcome from PROD!