gha-runner-scale-set:
  githubConfigUrl: "https://github.com/ibugithub/trykube"

  githubConfigSecret: arc-secret
  runnerScaleSetName: arc-runner-set
  minRunners: 1
  maxRunners: 5

  controllerServiceAccount:
    namespace: arc-systems
    name: arc-controller-gha-rs-controller

  template:
    metadata:
      annotations:
        actions.github.com/ttl: "300"