gha-runner-scale-set:
  githubConfigUrl: "https://github.com/ibugithub/trykube"

  githubConfigSecret: pre-defined-secret
  runnerScaleSetName: arc-runner-set
  minRunners: 1
  maxRunners: 5

  controllerServiceAccount:
    namespace: arc-systems
    name: arc-controller-gha-rs-controller

  template:
    metadata:
      annotations:
        actions.github.com/ttl: "300"
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"