helmCharts:
  - name: gha-runner-scale-set-controller 
    releaseName: arc-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: "0.12.0"
    namespace: arc-systems 
    includeCRDs: false
    valuesInline:
      scope:
        singleNamespace: false

resources:
  - namespaces.yaml
  - crds/actions.github.com_autoscalinglisteners.yaml
  - crds/actions.github.com_autoscalingrunnersets.yaml
  - crds/actions.github.com_ephemeralrunners.yaml
  - crds/actions.github.com_ephemeralrunnersets.yaml