apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - rolebinding.yaml

helmCharts:
  - name: gha-runner-scale-set-controller 
    releaseName: arc-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: "0.12.0"
    namespace: arc-systems 
    includeCRDs: true
    valuesInline:
      scope:
        singleNamespace: false
