apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
---
apiVersion: v1
kind: ServiceAccount
metadata:
  finalizers:
  - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: arc-runner-set
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/instance: arc-runner-set
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-runner-set
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.11.0
    helm.sh/chart: gha-rs-0.11.0
  name: arc-runner-set-gha-rs-no-permission
  namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  finalizers:
  - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: arc-runner-set
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/component: manager-role
    app.kubernetes.io/instance: arc-runner-set
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-runner-set
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.11.0
    helm.sh/chart: gha-rs-0.11.0
  name: arc-runner-set-gha-rs-manager
  namespace: arc-runners
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  finalizers:
  - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: arc-runner-set
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/component: manager-role-binding
    app.kubernetes.io/instance: arc-runner-set
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-runner-set
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.11.0
    helm.sh/chart: gha-rs-0.11.0
  name: arc-runner-set-gha-rs-manager
  namespace: arc-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner-set-gha-rs-manager
subjects:
- kind: ServiceAccount
  name: arc-gha-controller
  namespace: arc-systems
---
apiVersion: v1
data:
  existingSecret: YXJjLXNlY3JldA==
  github_token: dXNlLWZyb20tc2VjcmV0
kind: Secret
metadata:
  finalizers:
  - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: arc-runner-set
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/instance: arc-runner-set
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-runner-set
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.11.0
    helm.sh/chart: gha-rs-0.11.0
  name: arc-runner-set-gha-rs-github-secret
  namespace: arc-runners
---
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  annotations:
    actions.github.com/cleanup-github-secret-name: arc-runner-set-gha-rs-github-secret
    actions.github.com/cleanup-manager-role-binding: arc-runner-set-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: arc-runner-set-gha-rs-manager
    actions.github.com/cleanup-no-permission-service-account-name: arc-runner-set-gha-rs-no-permission
    actions.github.com/values-hash: 1eaf2dc43d438af9e308bac551bef04e599400dac37a8fe1b133d91ef1b9f56
  labels:
    actions.github.com/scale-set-name: arc-runner-set
    actions.github.com/scale-set-namespace: arc-runners
    app.kubernetes.io/component: autoscaling-runner-set
    app.kubernetes.io/instance: arc-runner-set
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-runner-set
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.11.0
    helm.sh/chart: gha-rs-0.11.0
  name: arc-runner-set
  namespace: arc-runners
spec:
  githubConfigSecret: arc-runner-set-gha-rs-github-secret
  githubConfigUrl: https://github.com/ibugithub/trykube
  runnerScaleSetName: arc-runner-set
  template:
    spec:
      containers:
      - name: runner
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
      restartPolicy: Never
      serviceAccountName: arc-runner-set-gha-rs-no-permission
