apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: arc-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/namespace: arc-systems
    app.kubernetes.io/part-of: gha-rs-controller
    app.kubernetes.io/version: 0.12.0
    helm.sh/chart: gha-rs-controller-0.12.0
  name: arc-gha-controller
  namespace: arc-systems
---
apiVersion: v1
kind: ServiceAccount
metadata:
  finalizers:
  - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: arc-stack
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/instance: arc-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-stack
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.12.0
    helm.sh/chart: gha-rs-controller-0.12.0
  name: arc-stack-gha-rs-controller-no-permission
  namespace: arc-systems
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-gha-controller-listener
  namespace: arc-systems
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  finalizers:
  - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: arc-stack
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: manager-role
    app.kubernetes.io/instance: arc-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-stack
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.12.0
    helm.sh/chart: gha-rs-controller-0.12.0
  name: arc-stack-gha-rs-controller-manager
  namespace: arc-systems
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arc-gha-controller
rules:
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-gha-controller-listener
  namespace: arc-systems
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-gha-controller-listener
subjects:
- kind: ServiceAccount
  name: arc-gha-controller
  namespace: arc-systems
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  finalizers:
  - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: arc-stack
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: manager-role-binding
    app.kubernetes.io/instance: arc-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-stack
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.12.0
    helm.sh/chart: gha-rs-controller-0.12.0
  name: arc-stack-gha-rs-controller-manager
  namespace: arc-systems
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-stack-gha-rs-controller-manager
subjects:
- kind: ServiceAccount
  name: arc-gha-controller
  namespace: arc-systems
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arc-gha-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arc-gha-controller
subjects:
- kind: ServiceAccount
  name: arc-gha-controller
  namespace: arc-systems
---
apiVersion: v1
data:
  existingSecret: YXJjLXNlY3JldA==
  github_token: dXNlLWZyb20tc2VjcmV0
kind: Secret
metadata:
  finalizers:
  - actions.github.com/cleanup-protection
  labels:
    actions.github.com/scale-set-name: arc-stack
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/instance: arc-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-stack
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.12.0
    helm.sh/chart: gha-rs-controller-0.12.0
  name: arc-stack-gha-rs-controller-github-secret
  namespace: arc-systems
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    actions.github.com/controller-service-account-name: arc-gha-controller
    actions.github.com/controller-service-account-namespace: arc-systems
    app.kubernetes.io/instance: arc-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/namespace: arc-systems
    app.kubernetes.io/part-of: gha-rs-controller
    app.kubernetes.io/version: 0.12.0
    helm.sh/chart: gha-rs-controller-0.12.0
  name: arc-gha-controller
  namespace: arc-systems
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: arc-stack
      app.kubernetes.io/name: gha-rs-controller
      app.kubernetes.io/namespace: arc-systems
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: arc-stack
        app.kubernetes.io/name: gha-rs-controller
        app.kubernetes.io/namespace: arc-systems
        app.kubernetes.io/part-of: gha-rs-controller
        app.kubernetes.io/version: 0.12.0
    spec:
      containers:
      - args:
        - --auto-scaling-runner-set-only
        - --log-level=debug
        - --log-format=text
        - --runner-max-concurrent-reconciles=2
        - --update-strategy=immediate
        - --listener-metrics-addr=0
        - --listener-metrics-endpoint=
        - --metrics-addr=0
        command:
        - /manager
        env:
        - name: CONTROLLER_MANAGER_CONTAINER_IMAGE
          value: ghcr.io/actions/gha-runner-scale-set-controller:0.12.0
        - name: CONTROLLER_MANAGER_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/actions/gha-runner-scale-set-controller:0.12.0
        imagePullPolicy: IfNotPresent
        name: manager
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      serviceAccountName: arc-gha-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: tmp
---
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  annotations:
    actions.github.com/cleanup-github-secret-name: arc-stack-gha-rs-controller-github-secret
    actions.github.com/cleanup-manager-role-binding: arc-stack-gha-rs-controller-manager
    actions.github.com/cleanup-manager-role-name: arc-stack-gha-rs-controller-manager
    actions.github.com/cleanup-no-permission-service-account-name: arc-stack-gha-rs-controller-no-permission
    actions.github.com/values-hash: 8cc179c8e3d1b6e4823c5a9366303759fe3a0fdb2fadec48e68fb6bc6c1c3e8
  labels:
    actions.github.com/scale-set-name: arc-stack
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: autoscaling-runner-set
    app.kubernetes.io/instance: arc-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arc-stack
    app.kubernetes.io/part-of: gha-rs
    app.kubernetes.io/version: 0.12.0
    helm.sh/chart: gha-rs-controller-0.12.0
  name: arc-stack
  namespace: arc-systems
spec:
  githubConfigSecret: arc-stack-gha-rs-controller-github-secret
  githubConfigUrl: https://github.com/ibugithub/trykube
  template:
    spec:
      containers:
      - name: runner
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
      restartPolicy: Never
      serviceAccountName: arc-stack-gha-rs-controller-no-permission
