apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-exercise-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-exercise-app
  template:
    metadata:
      labels:
        app: learning-exercise-app
    spec:
      serviceAccountName: le-sa
      containers:
        - name: learning-exercise-container 
          image: "156583401143.dkr.ecr.us-east-2.amazonaws.com/exercises-learning-ecr:latest"
          ports:
            - containerPort: 8000

          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: learning-exercise-app-config
                  key: WELCOME_MESSAGE