apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: learning-exercise-namespace

resources:
  - namespace.yaml
  - serviceAccount.yaml
  - configMap.yaml
  - deployment.yml
  - service.yaml
