apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: learning-exercise-app-config
    literals:
      - WELCOME_MESSAGE=REPLACE

resources:
  - deployment.yml
  - service.yaml
  - serviceAccount.yaml
