apiVersion: v1
kind: Service
metadata:
  name: learning-exercise-service
spec:
  type: LoadBalancer
  selector:
    app: learning-exercise-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000